In [17]:
#we can have 2D list:
my_list = [[True,2],[5,"v",33,56]]
print("my 2D list       :", my_list)

#similarly we can have 2D arrays:
import numpy as np
my_array = np.array([[1,3],[2,0,22,4]])
print("my 2D numpy array:",my_array)
calc_array = my_array * 3
print ("calculated array   :",calc_array)

#keep in mind 2D numpy arrays need to be in a nxn matrix format, otherwise
#python will create a array containing multiple lists
#example: 
#my_array = np.array([[1,3],[2,0,22,4]])  - is an array containing two lists
#my_array = np.array([[1,3],[2,0]])       - is a pure 2D array

my 2D list       : [[True, 2], [5, 'v', 33, 56]]
my 2D numpy array: [[1, 3] [2, 0, 22, 4]]
calculated array   : [[1, 3, 1, 3, 1, 3] [2, 0, 22, 4, 2, 0, 22, 4, 2, 0, 22, 4]]


In [25]:
#seems like 2D numpy arrays do not follow the same calculation method as lists
import numpy as np
ma0 = [1,2,3,4,5,6]
ma1 = np.array([[1,3],[2,0,22,4]])
ma2 = np.array([1,3,2,0,22,4])
print("ma0:",ma0)
print("m0_:",ma0*4)
print("ma1:",ma1)
print("ma1_:",ma1*2)
print("ma2:",ma2)
print("ma2_:",ma2*2)

ma0: [1, 2, 3, 4, 5, 6]
m0_: [1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6]
ma1: [[1, 3] [2, 0, 22, 4]]
ma1_: [[1, 3, 1, 3] [2, 0, 22, 4, 2, 0, 22, 4]]
ma2: [ 1  3  2  0 22  4]
ma2_: [ 2  6  4  0 44  8]


In [42]:
#accessing values in numpy array
import numpy as np
my_array = np.array([[1,3,4,4],[2,0,22,4]])
print(my_array)

[[ 1  3  4  4]
 [ 2  0 22  4]]


In [37]:
my_array[0]

array([1, 3, 3, 4])

In [38]:
my_array[1][1]

0

In [43]:
my_array[1,1]

0